export const clerkAppearance = {
  variables: {
    colorPrimary: "var(--color-action)",
    colorForeground: "var(--color-ink)",
    colorMutedForeground: "var(--color-muted)",
    colorBackground: "var(--color-surface)",
    colorInputBackground: "var(--color-surface)",
    colorInputText: "var(--color-ink)",
    colorDanger: "var(--color-danger)",
    borderRadius: "0.375rem",
    fontFamily: "var(--font-sans)",
  },
  elements: {
    rootBox: "!w-full !max-w-[420px]",
    cardBox: "!w-full !shadow-none",
    card: "!w-full !border-0 !bg-transparent !p-0 !shadow-none",
    headerTitle: "!font-display !text-3xl !font-semibold !tracking-[-0.03em] !text-ink",
    headerSubtitle: "!text-[15px] !leading-relaxed !text-muted",
    formButtonPrimary: "!min-h-[46px] !bg-action !font-semibold !shadow-none hover:!bg-action-hover active:!scale-[0.98]",
    formFieldInput: "!min-h-[46px] !border-line !shadow-none focus:!border-action focus:!ring-3 focus:!ring-action/15",
    formFieldLabel: "!font-semibold !text-ink",
    socialButtonsBlockButton: "!min-h-[46px] !border-line !shadow-none active:!scale-[0.98]",
    footerActionLink: "!font-semibold !text-action hover:!text-action-hover",
  },
};
